help:  		## Print this message
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend:  ## Install Frontend component
	@echo Installing Frontend
catalogue: ## Install Catalogue component
	@echo Installing Catalogue
cart:      ## Install Cart component
	@echo Installing Cart
user:      ## Install User component
	@echo Installing User
shipping:  ## Install Shipping component
	@echo Installing Shipping
payment:   ## Install Payment component
	@echo Installing Payment
mongodb:   ## Install Mongodb component
	@echo Installing Mongodb
redis:     ## Install Redis component
	@echo Installing Redis
mysql:     ## Install MySQL component
	@echo Installing MySQL
rabbitmq:  ## Install Rabbitmq component
	@echo Installing Rabbitmq

